"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Upload, AlertTriangle, CheckCircle, Smartphone, ArrowLeft } from "lucide-react"
import Link from "next/link"

export default function FakePaymentDetector() {
    const [analyzing, setAnalyzing] = useState(false)
    const [result, setResult] = useState<'safe' | 'fake' | null>(null)

    const handleAnalyze = () => {
        setAnalyzing(true)
        setTimeout(() => {
            setAnalyzing(false)
            setResult('fake') // Mock result
        }, 2000)
    }

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6 flex flex-col items-center">
            <div className="max-w-3xl w-full">
                <Button variant="ghost" asChild className="mb-6">
                    <Link href="/"><ArrowLeft className="mr-2 h-4 w-4" /> Back</Link>
                </Button>

                <div className="text-center mb-10">
                    <h1 className="text-4xl font-bold mb-2">Fake Payment Detector</h1>
                    <p className="text-muted-foreground">For Shopkeepers & Merchants: Verify if a screenshot is from a real payment app or a "Spoof" app.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                    <Card className="p-8 border-2 border-dashed border-slate-300 dark:border-slate-700 bg-slate-100 dark:bg-slate-900 text-center space-y-4 hover:border-primary transition-colors cursor-pointer" onClick={handleAnalyze}>
                        {analyzing ? (
                            <div className="py-12">
                                <div className="h-12 w-12 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                                <p className="text-lg font-medium animate-pulse">Scanning Pixels & Layout...</p>
                            </div>
                        ) : (
                            <>
                                <div className="bg-white dark:bg-slate-800 p-4 rounded-full w-20 h-20 mx-auto flex items-center justify-center shadow-lg">
                                    <Smartphone className="h-10 w-10 text-primary" />
                                </div>
                                <div>
                                    <h3 className="font-bold text-lg">Upload Payment Screenshot</h3>
                                    <p className="text-sm text-muted-foreground">or Drag & Drop here</p>
                                </div>
                                <Button variant="outline">Select Image</Button>
                            </>
                        )}
                    </Card>

                    {result === 'fake' && (
                        <div className="space-y-6 animate-in fade-in slide-in-from-right">
                            <Card className="bg-red-50 border-red-200 dark:bg-red-900/20 dark:border-red-800 p-6 text-center">
                                <div className="bg-red-100 dark:bg-red-900/40 p-3 rounded-full w-16 h-16 mx-auto flex items-center justify-center mb-4">
                                    <AlertTriangle className="h-8 w-8 text-red-600" />
                                </div>
                                <h2 className="text-2xl font-bold text-red-700 dark:text-red-400">FAKE DETECTED!</h2>
                                <p className="text-red-600 dark:text-red-300 mt-2">This screenshot was likely generated by a Spoof App.</p>
                            </Card>

                            <div className="space-y-2">
                                <p className="text-sm font-semibold">Why we flagged this:</p>
                                <div className="p-3 bg-white dark:bg-slate-900 border rounded flex items-center gap-2 text-sm text-red-600">
                                    <div className="h-2 w-2 rounded-full bg-red-500"></div> Incorrect Font Weight on "Success"
                                </div>
                                <div className="p-3 bg-white dark:bg-slate-900 border rounded flex items-center gap-2 text-sm text-red-600">
                                    <div className="h-2 w-2 rounded-full bg-red-500"></div> Missing Transaction ID watermark
                                </div>
                            </div>

                            <Button className="w-full bg-red-600 hover:bg-red-700" onClick={() => setResult(null)}>Scan Another</Button>
                        </div>
                    )}

                    {result === 'safe' && (
                        <div className="space-y-6 animate-in fade-in slide-in-from-right">
                            <Card className="bg-green-50 border-green-200 dark:bg-green-900/20 dark:border-green-800 p-6 text-center">
                                <div className="bg-green-100 dark:bg-green-900/40 p-3 rounded-full w-16 h-16 mx-auto flex items-center justify-center mb-4">
                                    <CheckCircle className="h-8 w-8 text-green-600" />
                                </div>
                                <h2 className="text-2xl font-bold text-green-700 dark:text-green-400">LOOKS AUTHENTIC</h2>
                                <p className="text-green-600 dark:text-green-300 mt-2">The layout matches official payment apps.</p>
                            </Card>
                            <Button className="w-full" onClick={() => setResult(null)}>Scan Another</Button>
                        </div>
                    )}

                    {!result && !analyzing && (
                        <div className="p-6 text-center text-muted-foreground">
                            <p>We check for:</p>
                            <ul className="list-disc list-inside text-sm mt-2 space-y-1">
                                <li>Incorrect Fonts</li>
                                <li>Missing Info Buttons</li>
                                <li>Alignment Errors</li>
                                <li>Known Spoof App Signatures</li>
                            </ul>
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}
